"""milestone 3: controls, control tests, actions

Revision ID: 250603a8466e
Revises: f150133b8154
Create Date: 2026-08-30 23:03:58.200677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '250603a8466e'
down_revision: Union[str, None] = 'f150133b8154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controls',
    sa.Column('control_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('control_type', sa.Enum('PREVENTIVE', 'DETECTIVE', 'CORRECTIVE', name='control_type'), nullable=False),
    sa.Column('automation', sa.Enum('MANUAL', 'AUTOMATED', name='control_automation'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('design_effectiveness', sa.Integer(), nullable=True),
    sa.Column('operating_effectiveness', sa.Integer(), nullable=True),
    sa.Column('last_tested', sa.Date(), nullable=True),
    sa.Column('next_test', sa.Date(), nullable=True),
    sa.Column('evidence', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'RETIRED', name='control_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controls_control_code'), 'controls', ['control_code'], unique=True)
    op.create_table('actions',
    sa.Column('action_code', sa.String(length=50), nullable=False),
    sa.Column('risk_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='action_priority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='action_status'), nullable=False),
    sa.Column('completion_percent', sa.Integer(), nullable=False),
    sa.Column('expected_risk_reduction', sa.Float(), nullable=True),
    sa.Column('evidence', sa.String(length=1000), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_action_code'), 'actions', ['action_code'], unique=True)
    op.create_table('control_tests',
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('tester', sa.String(length=300), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('test_method', sa.String(length=300), nullable=True),
    sa.Column('result', sa.Enum('EFFECTIVE', 'PARTIALLY_EFFECTIVE', 'INEFFECTIVE', 'NOT_TESTED', name='control_test_result'), nullable=False),
    sa.Column('evidence', sa.String(length=1000), nullable=True),
    sa.Column('finding', sa.Text(), nullable=True),
    sa.Column('remediation_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_controls',
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_id', 'control_id', name='uq_risk_control')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_controls')
    op.drop_table('control_tests')
    op.drop_index(op.f('ix_actions_action_code'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_controls_control_code'), table_name='controls')
    op.drop_table('controls')
    # ### end Alembic commands ###
