"""milestone 6-7 simulations and scenarios

Revision ID: 48f1d985d2d9
Revises: 7131532b9593
Create Date: 2026-08-31 19:15:33.919074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '48f1d985d2d9'
down_revision: Union[str, None] = '7131532b9593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assumptions', sa.Text(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('financial_impact_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('financial_impact_most_likely', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('financial_impact_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('operational_impact', sa.Text(), nullable=True),
    sa.Column('recovery_assumptions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_risks',
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'risk_id', name='uq_scenario_risk')
    )
    op.create_table('simulation_configs',
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('distribution_type', sa.Enum('TRIANGULAR', 'PERT', 'LOGNORMAL', name='simulation_distribution_type'), nullable=False),
    sa.Column('loss_min', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('loss_most_likely', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('loss_max', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('annual_event_frequency', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('correlation_group', sa.String(length=100), nullable=True),
    sa.Column('correlation_strength', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_runs',
    sa.Column('config_id', sa.UUID(), nullable=True),
    sa.Column('scenario_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='simulation_run_status'), nullable=False),
    sa.Column('iterations_used', sa.Integer(), nullable=False),
    sa.Column('seed_used', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['simulation_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_results',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('expected_annual_loss', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('median', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('p75', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('p90', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('p95', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('p99', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('histogram', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('per_risk_contribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_results')
    op.drop_table('simulation_runs')
    op.drop_table('simulation_configs')
    op.drop_table('scenario_risks')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
