"""milestone 4: snapshots, issues, incidents

Revision ID: a309942afad5
Revises: 250603a8466e
Create Date: 2026-08-30 23:43:28.862888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a309942afad5'
down_revision: Union[str, None] = '250603a8466e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshots',
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('incident_code', sa.String(length=50), nullable=False),
    sa.Column('risk_id', sa.UUID(), nullable=True),
    sa.Column('control_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='incident_severity'), nullable=False),
    sa.Column('suggests_likelihood_increase', sa.Boolean(), nullable=False),
    sa.Column('review_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_incident_code'), 'incidents', ['incident_code'], unique=True)
    op.create_table('issues',
    sa.Column('issue_code', sa.String(length=50), nullable=False),
    sa.Column('risk_id', sa.UUID(), nullable=True),
    sa.Column('control_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='issue_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_issue_code'), 'issues', ['issue_code'], unique=True)
    op.create_table('snapshot_risks',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('frozen_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshot_risks')
    op.drop_index(op.f('ix_issues_issue_code'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_incidents_incident_code'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_table('snapshots')
    # ### end Alembic commands ###
