"""initial milestone 1 schema

Revision ID: f150133b8154
Revises: 
Create Date: 2026-08-30 22:04:18.184418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f150133b8154'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('actor', sa.String(length=320), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('background_jobs',
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='job_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_categories',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['risk_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('name', sa.Enum('VIEWER', 'RISK_OWNER', 'CONTROL_OWNER', 'RISK_MANAGER', 'EXECUTIVE', 'ADMINISTRATOR', 'AUDITOR', name='role_name'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('sso_subject', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sso_subject')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('import_jobs',
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'MAPPED', 'VALIDATED', 'PREVIEWED', 'COMMITTING', 'COMMITTED', 'FAILED', name='import_job_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_appetite',
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('business_unit', sa.String(length=200), nullable=True),
    sa.Column('appetite_band', sa.String(length=50), nullable=False),
    sa.Column('tolerance_band', sa.String(length=50), nullable=False),
    sa.Column('limit_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['risk_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risks',
    sa.Column('risk_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('cause', sa.Text(), nullable=True),
    sa.Column('event', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('business_process', sa.String(length=300), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('accountable_executive_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'MONITORING', 'CLOSED', name='risk_status'), nullable=False),
    sa.Column('decision', sa.Enum('ACCEPT', 'TREAT', 'TRANSFER', 'AVOID', 'PENDING', name='risk_decision'), nullable=False),
    sa.Column('acceptance_rationale', sa.Text(), nullable=True),
    sa.Column('raised_date', sa.Date(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('likelihood', sa.Integer(), nullable=True),
    sa.Column('overall_impact', sa.Float(), nullable=True),
    sa.Column('inherent_score', sa.Float(), nullable=True),
    sa.Column('inherent_band', sa.Enum('LOW', 'MODERATE', 'HIGH', 'EXTREME', name='risk_band_inherent'), nullable=True),
    sa.Column('control_effectiveness', sa.Float(), nullable=True),
    sa.Column('residual_score', sa.Float(), nullable=True),
    sa.Column('residual_band', sa.Enum('LOW', 'MODERATE', 'HIGH', 'EXTREME', name='risk_band_residual'), nullable=True),
    sa.Column('velocity', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.String(length=50), nullable=True),
    sa.Column('treatment_summary', sa.Text(), nullable=True),
    sa.Column('latest_update', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accountable_executive_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['risk_categories.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_risk_code'), 'risks', ['risk_code'], unique=True)
    op.create_table('scoring_config',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('department_scope', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_column_mappings',
    sa.Column('import_job_id', sa.UUID(), nullable=False),
    sa.Column('source_column', sa.String(length=300), nullable=False),
    sa.Column('domain_field', sa.String(length=200), nullable=True),
    sa.Column('transform', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_row_errors',
    sa.Column('import_job_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=200), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_assessments',
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('overall_impact', sa.Float(), nullable=False),
    sa.Column('inherent_score', sa.Float(), nullable=False),
    sa.Column('inherent_band', sa.Enum('LOW', 'MODERATE', 'HIGH', 'EXTREME', name='risk_band_inherent'), nullable=False),
    sa.Column('control_effectiveness', sa.Float(), nullable=True),
    sa.Column('residual_score', sa.Float(), nullable=True),
    sa.Column('residual_band', sa.Enum('LOW', 'MODERATE', 'HIGH', 'EXTREME', name='risk_band_residual'), nullable=True),
    sa.Column('scoring_config_version', sa.Integer(), nullable=False),
    sa.Column('assessed_by', sa.UUID(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_history',
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('field_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=320), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_impact_scores',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.Enum('FINANCIAL', 'CUSTOMER_SERVICE', 'OPERATIONAL_DELIVERY', 'LEGAL_REGULATORY', 'REPUTATION', 'HEALTH_SAFETY', name='impact_dimension'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_impact_scores')
    op.drop_table('risk_history')
    op.drop_table('risk_assessments')
    op.drop_table('import_row_errors')
    op.drop_table('import_column_mappings')
    op.drop_table('user_roles')
    op.drop_table('scoring_config')
    op.drop_index(op.f('ix_risks_risk_code'), table_name='risks')
    op.drop_table('risks')
    op.drop_table('risk_appetite')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('risk_categories')
    op.drop_table('background_jobs')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
